### PR TITLE
New upstream version 5.0.23

### PR DESCRIPTION
**Pull request by zsien**
Fixes linuxdeepin/developer-center#3708

### CODE REVIEW

**Comment by Zeno-sole** [comment]
https://build.deepin.com/package/show/deepin:CI:deepin-community:fcitx5:PR-5/fcitx5

**Comment by Zeno-sole** [comment]
Files could not be expanded: service error: ' [less info](javascript:void(0))
service obs_gbp failed:
Command ['gbp', 'buildpackage', '--git-notify=off', '--git-force-create', '--git-cleaner="true"', '--git-upstream-tag=obsbuild/%(version)s', '--git-ignore-branch', '--git-export=origin/36efacbe5910495b3c63021ee3621c7aa1594d28', '--git-submodules', '--git-no-pristine-tar', '-nc', '-uc', '-us', '-S', '--git-ignore-new'] failed(1): 'gbp:info: Creating fcitx5_5.0.23.orig.tar.gz from 'obsbuild/5.0.23'
gbp:info: Performing the build
dpkg-buildpackage -us -uc -ui -i -I -nc -S
dpkg-buildpackage: info: source package fcitx5
dpkg-buildpackage: info: source version 5.0.23-0deepin
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by zsien
dpkg-source -i -I --before-build .
dpkg-source: info: using patch list from debian/patches/series
dpkg-source: info: applying 0001-dict-CMakeLists.txt-Use-dict-from-data-subdir.patch
dpkg-source: info: applying 0002-fix-kde-config-fcitx5-package-name-in-fcitx5-configtool.patch
dpkg-source: info: applying 0004-upgrade-cmake-minumum-version-require.patch
patching file CMakeLists.txt
Hunk #1 FAILED at 1.

**Comment by Zeno-sole** [comment]
@zsien patch应用失败 请检查patch是否pop

**Comment by zsien** [comment]
> @zsien patch应用失败 请检查patch是否pop

done

**Comment by UTsweetyfish** [comment]
/+1

**Review by tsic404 — APPROVED** [review]

**Pull request merged**
